### ISSUE TITLE
Empty string instead of empty array throws error in Contao 4.8.x

### ISSUE THREAD

**Issue by ben-eSM** [Kuestenschmiede/CoreBundle#5]
The following empty string instead of an empty array is throwing an error in Contao 4.8.x due to the new generic label handling for operations an global operations introduced in Contao 4.8.

https://github.com/Kuestenschmiede/CoreBundle/blob/5b61593f476f31280f6ddbc1a4dd8e5f717a7a64/Resources/contao/dca/tl_c4g_settings.php#L56

**Comment by coastforge-mei** [comment]
Thank you for your contribution. We have fixed the bug in v3.3.16.
